config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users

  # Defines the root path route ("/")
  root "home#index"

  namespace :api do
    resources :users, only: :show
    get "/users_by_email" => "users_by_emails#show", as: :users_by_email, format: :json

    resources :favorites, only: [:create, :destroy]
  end
  resources :properties, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :property
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  geocoded_by :address
  after_validation :geocode, if: -> { address.present? && latitude.blank? && longitude.blank? }

  def address
    [state, country].compact.join(', ')
  end
end

app/models/property.rb
class Property < ApplicationRecord
	validates :name, presence: true
	validates :headline, presence: true
	validates :description, presence: true
	validates :address_1, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :country, presence: true
	monetize :price_cents, allow_nil: true

	geocoded_by :address
	after_validation :geocode, if: -> { latitude.blank? && longitude.blank? }  


	has_many_attached :images, dependent: :destroy

	has_many :reviews, as: :reviewable
	has_many :favorites, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user
  has_many :reservations, dependent: :destroy
  has_many :reserved_users, through: :reservations, source: :user


	

	def address
	  [state, country].compact.join(', ')
	end

	def default_image
		images.first
	end
	
	def favorited_by?(user)
		return if user.nil?

		favorited_users.include?(user)
	end

  def available_dates
    next_reservation = reservations.future_reservations.first
    return Date.tomorrow.strftime("%b %e")..Date.today.end_of_year.strftime("%b %e") if next_reservation.nil?
    Date.tomorrow.strftime("%b %e")..next_reservation.reservation_date.strftime("%b %e")
  end
  
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :property
  belongs_to :user

  validates :reservation_date, presence: true 

  scope :future_reservations, -> { where("reservation_date > ?", Date.today).order(:reservation_date) }
end

app/models/review.rb
class Review < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
	validates :rating, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5, only_integer: true }

	belongs_to :reviewable, polymorphic: true, counter_cache: true

	after_commit :update_average_rating, on: [:create, :update]
	def update_average_rating
		reviewable.reviews.average(:rating)
		reviewable.update!(average_rating: reviewable.reviews.average(:rating))
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_properties, through: :favorites, source: :property
  has_many :reservations, dependent: :destroy
  has_many :reserved_properties, through: :reservations, source: :property

  after_create :create_profile

  def create_profile
    self.profile = Profile.new
    save!
  end
end

app/controllers/api/favorites_controller.rb
# forzen_string_literal: true

module Api
  class FavoritesController < ApplicationController
    protect_from_forgery with: :null_session

    # before_action :authenticate_user!

    def create
      favorite = Favorite.create!(favorite_params)

      respond_to do |format|
        format.json do
          render json: serialize_favorite(favorite), status: :created
        end
      end
    end

    def destroy
      favorite = Favorite.find(params[:id])
      favorite.destroy!

      respond_to do |format|
        format.json do
          render json: serialize_favorite(favorite), status: 204
        end
      end
    end

    private
    def favorite_params
      params.permit(:user_id, :property_id)
    end

    def serialize_favorite(favorite)
      FavoriteSerializer.new(favorite).serializable_hash[:data].to_json
    end
  end
end

app/controllers/api/users_by_emails_controller.rb
# frozen_string_literal: true

module Api
	class UsersByEmailsController < ApplicationController
		def show
			user = User.find_by!(email: params[:email])

			respond_to do |format|
				format.json do
					render json: user.to_json, status: :ok
				end
			end
		rescue ActiveRecord::RecordNotFound => e
			respond_to do |format|
				format.json do
					render json: { error: e.message }.to_json, status: :not_found
				end
			end
		end
	end
end

app/controllers/api/users_controller.rb
# frozen_string_literal: true

module Api
	class UsersController < ApplicationController
		def show
			user = User.find(params[:id])

			respond_to do |format|
				format.json do
					render json: user.to_json, status: :ok
				end
			end
		rescue ActiveRecord::RecordNotFound => e
			respond_to do |format|
				format.json do
					render json: { error: e.message }.to_json, status: :not_found
				end
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@properties = Property.all
	end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def show
    @property = Property.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_user_auth_form.html.erb
<div data-controller="users-by-email-auth">
  <div>
    <div class="flex">
      <div class="flex-none cursor-pointer" data-modal-target="closeButton">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </div>
      <div class="grow">
        <h3 class="text-md mb-4 text-center font-bold leading-6 text-gray-900" id="modal-title">Log in or sign up</h3>
      </div>
    </div>
    <div class="relative">
      <div class="absolute inset-0 flex items-center" aria-hidden="true">
        <div class="w-full border-t border-gray-300"></div>
      </div>
    </div>

    <div class="pt-4">
      <h4 class="text-xl leading-6 text-gray-900 mt-2 font-semibold">Welcome to Airbnb</h4>
      <!--
                  This example requires some changes to your config:
                  
                  ```
                  // tailwind.config.js
                  module.exports = {
                    // ...
                    plugins: [
                      // ...
                      require('@tailwindcss/forms'),
                    ],
                  }
                  ```
                -->
      <div data-users-by-email-auth-target="emailWrapper" class="relative mt-6 rounded-md border border-gray-300 px-3 py-2 shadow-sm focus-within:border-black focus-within:ring-1 focus-within:ring-black">
        <label for="email" class="block text-xs font-medium text-gray-900">Email</label>
        <input data-users-by-email-auth-target="email" type="text" name="email" id="email" class="block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm" placeholder="Jane.smith@gmail.com" />
            <div data-users-by-email-auth-target="invalidSvg" class="hidden pointer-events-none absolute inset-y-0 right-0 flex items-center pr-3">
              <!-- Heroicon name: mini/exclamation-circle -->
              <svg class="h-5 w-5 text-red-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-5a.75.75 0 01.75.75v4.5a.75.75 0 01-1.5 0v-4.5A.75.75 0 0110 5zm0 10a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd" />
              </svg>
            </div>
      </div>
        <p data-users-by-email-auth-target="errorMsg" class="hidden mt-2 text-sm text-red-600" id="email-error">Please enter a valid email address.</p>
    </div>
  </div>
  <div class="my-5 sm:my-6">
    <button
      data-users-by-email-auth-target="submit"
      type="button"
      class="w-full justify-center inline-flex items-center rounded-md border border-transparent px-6 py-3 text-base font-medium text-white shadow-sm focus:outline-none focus:ring-2 airbnb-pink-gradient focus:ring-offset-2"
    >
      Continue
    </button>
  </div>
</div>
<div class="relative">
  <div class="absolute inset-0 flex items-center" aria-hidden="true">
    <div class="w-full border-t border-gray-300"></div>
  </div>
  <div class="relative flex justify-center">
    <span class="bg-white px-2 text-sm text-gray-500">or</span>
  </div>
</div>
<div class="mt-5 sm:mt-6">
  <button
    type="button"
    class="w-full justify-center inline-flex items-center rounded-md border-2 border-solid border-gray-900 bg-white px-6 py-3 text-base font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 font-semibold"
  >
    Continue with Facebook
  </button>
</div>

app/views/home/index.html.erb
<div 
	data-controller="geolocation" 
	class="container mx-auto py-16" 
	data-latitude="<%= current_user&.profile&.latitude %>" 
	data-longitude="<%= current_user&.profile&.longitude %>"
>
	<ul role="list" class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-4 sm:gap-x-6 lg:grid-cols-5 xl:gap-x-8">
		<% @properties.each do |property| %>
		<%= link_to property_path(property) do %>
			  <li 
			  class="relative"
			  data-geolocation-target="property"
			  data-latitude="<%= property.latitude %>"
			  data-longitude="<%= property.longitude %>"
			  >
			  	 <div class="group aspect-w-10 aspect-h-7 block w-full overflow-hidden rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 focus-within:ring-offset-gray-100">
			      <%= image_tag property.default_image, class: "pointer-events-none object-cover group-hover:opacity-75" %>
			      <button type="button" class="absolute inset-0 focus:outline-none">
			        <span class="sr-only">View details for IMG_4985.HEIC</span>
			      </button>
			      <div class="flex flex-row-reverse p-2">
			      	<svg 
				      	xmlns="http://www.w3.org/2000/svg" 
				      	fill="<%= property.favorited_by?(current_user) ? 'black' : "#ced4da" %>"
				      	viewBox="0 0 24 24"
				      	data-controller="favorites"
				      	data-user-logged-in="<%= user_signed_in? %>"
				      	data-user-id="<%= current_user&.id %>"
				      	data-property-id="<%= property.id %>"
				      	data-favorite-id="<%= property.favorites.find_by(user: current_user)&.id %>"
				      	data-favorited="<%= property.favorited_by?(current_user) %>"
				      	data-action="click->favorites#favorite"
				      	stroke-width="1.5" 
				      	stroke="currentColor" 
				      	class="w-6 h-6 text-white cursor-pointer"
			      	>
					  <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
					</svg>
							<!-- <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5">
							  <path d="M11.645 20.91l-.007-.003-.022-.012a15.247 15.247 0 01-.383-.218 25.18 25.18 0 01-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0112 5.052 5.5 5.5 0 0116.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 01-4.244 3.17 15.247 15.247 0 01-.383.219l-.022.012-.007.004-.003.001a.752.752 0 01-.704 0l-.003-.001z" />
							</svg> -->
			      </div>
			    </div>
			    <p class="pointer-events-none mt-2 block truncate text-sm font-medium text-gray-900"><%=property.city %>, <%= property.state %>, <%= property.country %></p>
			    <p class="pointer-events-none block text-sm font-medium text-gray-500 text-black"><%= property.average_rating.round(2) %>
			    	<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4 inline-block relative" style="bottom: 2px;">
					  <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
					</svg>
			    </p>
			    <p data-distance-away class="pointer-events-none block text-sm font-medium text-gray-500"></p>
			    <p class="pointer-events-none block text-sm font-medium text-gray-500"><%= property.available_dates.first%> - <%= property.available_dates.last%> </p>
			    <p class="pointer-events-none block text-sm font-medium text-gray-500"><span class="text-black"><%= humanized_money_with_symbol(property.price) %></span> per night</p>
			  </li>
		  <% end %>
		<% end %>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/properties/_share_property.html.erb
<div 
  data-controller="share-modal"
  data-share-url="<%= url_for(only_path: false) %>"
>
    <div class="flex">
      <div class="flex-none cursor-pointer" data-modal-target="closeButton">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </div>
      <div class="grow">
        <p class="text-md mb-4 text-center text-2xl font-medium leading-6 text-gray-900" id="modal-title">Share this place with friends and family.</p>
      </div>
    </div>
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 mb-4">
      <div class="relative flex items-center space-x-3 mt-2">
        <div class="flex-shrink-0">
          <img class="h-16 w-16 rounded-lg" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
        </div>
        <div class="min-w-0 flex-1">
            <p class="text-sm font-normal text-gray-900"><%= @property.name %></p>
        </div>
      </div>
      <!-- More people... -->
    </div>
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
      <div data-action="click->share-modal#copyLink" class="relative flex items-center cursor-pointer space-x-3 rounded-lg border border-gray-300 bg-white px-4 py-5 shadow-sm hover:bg-gray-100">
        <div class="flex-shrink-0">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 17.25v3.375c0 .621-.504 1.125-1.125 1.125h-9.75a1.125 1.125 0 01-1.125-1.125V7.875c0-.621.504-1.125 1.125-1.125H6.75a9.06 9.06 0 011.5.124m7.5 10.376h3.375c.621 0 1.125-.504 1.125-1.125V11.25c0-4.46-3.243-8.161-7.5-8.876a9.06 9.06 0 00-1.5-.124H9.375c-.621 0-1.125.504-1.125 1.125v3.5m7.5 10.375H9.375a1.125 1.125 0 01-1.125-1.125v-9.25m12 6.625v-1.875a3.375 3.375 0 00-3.375-3.375h-1.5a1.125 1.125 0 01-1.125-1.125v-1.5a3.375 3.375 0 00-3.375-3.375H9.75" />
          </svg>

        </div>
        <div class="min-w-0 flex-1">
          <span class="absolute inset-0" aria-hidden="true"></span>
          <p class="text-sm font-medium text-gray-900">Copy Link</p>
        </div>
      </div>

      <!-- More people... -->

      <div data-action="click->share-modal#shareWhatsApp" class="relative flex items-center cursor-pointer space-x-3 rounded-lg border border-gray-300 bg-white px-4 py-5 shadow-sm hover:bg-gray-100">
        <div class="flex-shrink-0">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" stroke-width="1" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M380.9 97.1C339 55.1 283.2 32 223.9 32c-122.4 0-222 99.6-222 222 0 39.1 10.2 77.3 29.6 111L0 480l117.7-30.9c32.4 17.7 68.9 27 106.1 27h.1c122.3 0 224.1-99.6 224.1-222 0-59.3-25.2-115-67.1-157zm-157 341.6c-33.2 0-65.7-8.9-94-25.7l-6.7-4-69.8 18.3L72 359.2l-4.4-7c-18.5-29.4-28.2-63.3-28.2-98.2 0-101.7 82.8-184.5 184.6-184.5 49.3 0 95.6 19.2 130.4 54.1 34.8 34.9 56.2 81.2 56.1 130.5 0 101.8-84.9 184.6-186.6 184.6zm101.2-138.2c-5.5-2.8-32.8-16.2-37.9-18-5.1-1.9-8.8-2.8-12.5 2.8-3.7 5.6-14.3 18-17.6 21.8-3.2 3.7-6.5 4.2-12 1.4-32.6-16.3-54-29.1-75.5-66-5.7-9.8 5.7-9.1 16.3-30.3 1.8-3.7.9-6.9-.5-9.7-1.4-2.8-12.5-30.1-17.1-41.2-4.5-10.8-9.1-9.3-12.5-9.5-3.2-.2-6.9-.2-10.6-.2-3.7 0-9.7 1.4-14.8 6.9-5.1 5.6-19.4 19-19.4 46.3 0 27.3 19.9 53.7 22.6 57.4 2.8 3.7 39.1 59.7 94.8 83.8 35.2 15.2 49 16.5 66.6 13.9 10.7-1.6 32.8-13.4 37.4-26.4 4.6-13 4.6-24.1 3.2-26.4-1.3-2.5-5-3.9-10.5-6.6z"/></svg>
        </div>
        <div class="min-w-0 flex-1">
          <a href="#" class="focus:outline-none">
            <span class="absolute inset-0" aria-hidden="true"></span>
            <p class="text-sm font-medium text-gray-900">WhatsApp</p>
          </a>
        </div>
      </div>

      <div data-action="click->share-modal#shareFacebook" class="relative flex items-center cursor-pointer space-x-3 rounded-lg border border-gray-300 bg-white px-4 py-5 shadow-sm hover:bg-gray-100">
        <div class="flex-shrink-0">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" stroke-width="1" viewBox="0 0 320 512"><!-- Font Awesome Pro 5.15.4 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) --><path d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"/></svg>
        </div>
        <div class="min-w-0 flex-1">
          <a href="#" class="focus:outline-none">
            <span class="absolute inset-0" aria-hidden="true"></span>
            <p class="text-sm font-medium text-gray-900">Facebook</p>
          </a>
        </div>
      </div>

      <div data-action="click->share-modal#shareTwitter" class="relative flex items-center cursor-pointer space-x-3 rounded-lg border border-gray-300 bg-white px-4 py-5 shadow-sm hover:bg-gray-100">
        <div class="flex-shrink-0">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" stroke-width="1" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"/></svg>
        </div>
        <div class="min-w-0 flex-1">
          <a href="#" class="focus:outline-none">
            <span class="absolute inset-0" aria-hidden="true"></span>
            <p class="text-sm font-medium text-gray-900">Twitter</p>
          </a>
        </div>
      </div>
</div>

app/views/shared/_modal.html.erb
<div 
  data-controller="modal"
  data-modal-trigger-id="<%= modal_trigger_id %>"
  id="modal-<%=modal_trigger_id %>-wrapper" 
  class="hidden relative z-10" 
  aria-labelledby="modal-title" 
  role="dialog" 
  aria-modal="true"
>
  <div class="hidden" id="<%= modal_trigger_id %>" data-action="click->modal#showModal"></div>
  <!--
    Background backdrop, show/hide based on modal state.

    Entering: "ease-out duration-300"
      From: "opacity-0"
      To: "opacity-100"
    Leaving: "ease-in duration-200"
      From: "opacity-100"
      To: "opacity-0"
  -->
  <div
    id="modal-<%=modal_trigger_id %>-backdrop"
    class="hidden fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
    data-transition-enter="ease-out duration-300"
    data-transition-enter-start="opacity-0"
    data-transition-enter-end="opacity-100"
    data-transition-leave="ease-in duration-200"
    data-transition-leave-start="opacity-100"
    data-transition-leave-end="opacity-0"
  ></div>

  <div class="fixed inset-0 z-10 overflow-y-auto">
    <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
      <!--
        Modal panel, show/hide based on modal state.

        Entering: "ease-out duration-300"
          From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
          To: "opacity-100 translate-y-0 sm:scale-100"
        Leaving: "ease-in duration-200"
          From: "opacity-100 translate-y-0 sm:scale-100"
          To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
      -->
      <div
        id="modal-<%=modal_trigger_id %>-panel"
        data-transition-enter="ease-out duration-300"
        data-transition-enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        data-transition-enter-end="opacity-100 translate-y-0 sm:scale-100"
        data-transition-leave="ease-in duration-200"
        data-transition-leave-start="opacity-100 translate-y-0 sm:scale-100"
        data-transition-leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        class="hidden relative transform overflow-hidden rounded-lg bg-white px-4 pt-5 pb-4 text-left shadow-xl transition-all sm:my-8 sm:max-w-xl sm:w-full sm:p-6"
      >
        <%= render modal_content %>
      </div>
    </div>
  </div>
</div>